/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service
 * User management service with RabbitMQ and Redis integration
 * OpenAPI spec version: 1.0.0
 */
import type {
  LogoutResponse,
  RefreshRequest,
  RequestOTPRequest,
  RequestOTPResponse,
  TokenResponse,
  VerifyOTPRequest,
  VerifyOTPResponse
} from './api.schemas';

import { axiosInstance } from '../../../lib/axiosClient';



  export const getUserService = () => {
/**
 * Request an OTP to be sent to the user's email or phone
 * @summary Request Otp
 */
const requestOtpApi = (
    requestOTPRequest: RequestOTPRequest,
 ) => {
      return axiosInstance<RequestOTPResponse>(
      {url: `/auth/request-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestOTPRequest
    },
      );
    }
  
/**
 * Verify OTP and authenticate user. Creates new user if doesn't exist.
 * @summary Verify Otp
 */
const verifyOtpApi = (
    verifyOTPRequest: VerifyOTPRequest,
 ) => {
      return axiosInstance<VerifyOTPResponse>(
      {url: `/auth/verify-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyOTPRequest
    },
      );
    }
  
/**
 * @summary Refresh Token
 */
const refreshTokenApi = (
    refreshRequest: RefreshRequest,
 ) => {
      return axiosInstance<TokenResponse>(
      {url: `/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  
/**
 * @summary Logout
 */
const logoutApi = (
    refreshRequest: RefreshRequest,
 ) => {
      return axiosInstance<LogoutResponse>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  
return {requestOtpApi,verifyOtpApi,refreshTokenApi,logoutApi}};
export type RequestOtpApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['requestOtpApi']>>>
export type VerifyOtpApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['verifyOtpApi']>>>
export type RefreshTokenApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['refreshTokenApi']>>>
export type LogoutApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['logoutApi']>>>
