/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service
 * User management service with RabbitMQ and Redis integration
 * OpenAPI spec version: 1.0.0
 */
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LogoutResponse {
  msg: string;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface RequestOTPRequest {
  identifier: string;
}

export interface RequestOTPResponse {
  message: string;
  identifier_type: string;
}

export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleEnum = {
  user: 'user',
  group_admin: 'group_admin',
} as const;

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
}

export type UserOutEmail = string | null;

export interface UserOut {
  id: string;
  name: string;
  phone_number: string;
  email: UserOutEmail;
  role: RoleEnum;
  profile_image?: string;
}

export type UserUpdateName = string | null;

export type UserUpdatePhoneNumber = string | null;

export type UserUpdateEmail = string | null;

export type UserUpdateAvatarUrl = string | null;

export type UserUpdateCardNumber = string | null;

export type UserUpdateCardHolderName = string | null;

export interface UserUpdate {
  name?: UserUpdateName;
  phone_number?: UserUpdatePhoneNumber;
  email?: UserUpdateEmail;
  profile_image?: UserUpdateAvatarUrl;
  card_number?: UserUpdateCardNumber;
  card_holder_name?: UserUpdateCardHolderName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface VerifyOTPRequest {
  identifier: string;
  otp_code: string;
}

export interface VerifyOTPResponse {
  access_token: string;
  refresh_token: string;
  is_new_user: boolean;
}

