/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service
 * User management service with RabbitMQ and Redis integration
 * OpenAPI spec version: 1.0.0
 */
import type {
  UserOut,
  UserUpdate
} from './api.schemas';

import { axiosInstance } from '../../../lib/axiosClient';



  export const getUserService = () => {
/**
 * @summary Get Current User Info
 */
const getProfileApi = (
    
 ) => {
      return axiosInstance<UserOut>(
      {url: `/users/profile`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update User Profile
 */
const updateProfileApi = (
    userUpdate: UserUpdate,
 ) => {
      return axiosInstance<UserOut>(
      {url: `/users/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate
    },
      );
    }
  
return {getProfileApi,updateProfileApi}};
export type GetProfileApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['getProfileApi']>>>
export type UpdateProfileApiResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUserService>['updateProfileApi']>>>
